### PR TITLE
Upgrade clap to 3.0 and fix (most) clippy warnings

### PR DESCRIPTION
**Pull request by jplatte**

### CODE REVIEW

**Comment by anuejn** [comment]
nice, thanks a lot :)

**Comment by anuejn** [comment]
merged this maually :)

**Comment by jplatte** [comment]
Oh, was about to push a rebased version 😅

**Comment by anuejn** [comment]
sorry for being so fast then, wanted to push to your branch but i somehow fucked up my git foo :(

**Pull request closed without merging**
